work_dir: ./work_dir/ntu60/xsub/bone_motion

# feeder
# change feeder to feeders.dummy_feeder_ntu.Feeder for model testing
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: True

test_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: True
  bone: True
  debug: False

# model
model: model.MSGCN_main.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [70, 90, 110, 130, 150, 170]
warm_up_epoch: 5

# training
device: 1
batch_size: 128
test_batch_size: 128
num_epoch: 190
nesterov: True